title: "Boosters Tech"
email: tech.operation@boosters.kr
timezone: UTC
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/custom/tech_a_bk.png'
favicon: 'assets/images/custom/favicon.ico'
author: tech
paginate_path: "/page:num/"
paginate: 10
disqus: 'boosters-labs'
locale: ko_kr
lang: ko_kr
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
collections:
  posts:
    output: true
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
# ganalytics: UA-113961478-1

# Authors
authors:
  tech:
    name: Tech Team
    display_name: Tech Team
    avatar: 'assets/images/sal.png'
    email: operation.tech@boosters.kr
    description: ""
  dilee:
    name: Lee Dong il
    display_name: Dongil.lee
    avatar: 'assets/images/sal.png'
    email: di.lee@boosters.kr
    description: "부스터스 Tech팀의 리더 역할을 하고 있습니다. 팀을 더 윤기나게 만드는 살림꾼 역할을 하는 리더이고 싶습니다."
  yjkim:
    name: Kim Yu jin
    display_name: Yujin.kim
    avatar: 'assets/images/미모티콘-유진.jpg'
    email: yujin.kim@boosters.kr
    description: "부스터스 Tech팀에서 프론트엔드를 맡고 있습니다. 데이터 정보를 시각적으로 예쁘고 사용자 친화적으로 변환하는 일을 하고 있습니다."
  sekim:
    name: Kim Seung Eon
    display_name: Seungeon.kim
    avatar: 'assets/images/sal.png'
    email: se.kim@boosters.kr
    description: "부스터스 Tech팀에서 백엔드를 맡고 있습니다."
  twkim:
    name: Kim Tae Woo
    display_name: Taewoo.kim
    avatar: 'assets/images/sal.png'
    email: tw.kim@boosters.kr
    description: "부스터스 Tech팀에서 백엔드를 맡고 있습니다."

    # web: https://www.wowthemes.net/category/jekyll-themes/
    # twitter: https://twitter.com/wowthemesnet

# Social
social:
  # instagram: https://www.instagram.com/bootstrapstarter/
  # facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  # twitter: https://twitter.com/bstartercom

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
